# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Process pr or push to master/prod

on:
  push:
    branches:
      - master
      - prod
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: "16.x"

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Resolve Project Dependencies Using Yarn"
        shell: pwsh
        run: |
          yarn
      - name: "Run linter"
        shell: pwsh
        run: |
          yarn lint
  test:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Resolve Project Dependencies Using Yarn"
        shell: pwsh
        run: |
          yarn
      - name: "Run tests"
        shell: pwsh
        run: |
          yarn test

  build-and-deploy:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod'
    runs-on: windows-latest
    needs:
      - lint
      - test
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Yarn"
        shell: pwsh
        run: |
          yarn
          yarn build

      - name: "Create zip"
        run: |
          Get-ChildItem $pwd | Compress-Archive -Destination .\favservice.zip
        shell: pwsh

      - name: "Deploy the zip to dev"
        if: github.ref == 'refs/heads/master'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'digitransit-dev2-fav-service'
          slot-name: 'swap'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV_2024 }}
          package: ./favservice.zip

      - name: "Deploy the zip to prod"
        if: github.ref == 'refs/heads/prod'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'digitransit-prod-fav-service'
          slot-name: 'pre-prod'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PROD_2024 }}
          package: ./favservice.zip
